// LeetCode-1244: https://leetcode.com/problems/design-a-leaderboard/

// Premium
// Companies: [Pinterest][Bloomberg][Uber][Amazon][Google][DE Shaw][Wayfair]

// barely passes: bottom 5 %tile in speed

#include <vector>
#include <unordered_map>
#include <unordered_set>
#include <queue>
#include <list>

using namespace std;

class PlayerScore {
private:
    PlayerScore(int player, int score) {
        this->player = player;
        this->score = score;
    }

public:
    int score;
    int player;

    PlayerScore() : score(0), player(0) {}  // default constructor

    static PlayerScore of(int player, int score) {
        return PlayerScore(player, score);
    }

    static PlayerScore of(int player) {
        return PlayerScore(player, 0);
    }

    PlayerScore withUpdatedScore(int score) {
        PlayerScore newPlayerScore = PlayerScore(this->player, score);
        return newPlayerScore;
    }

    PlayerScore withResetScore() {
        return withUpdatedScore(0);
    }
};

// Comparator for descending order of score (Generated by Microsoft Copilot)
struct CompareScore {
    bool operator()(const PlayerScore& a, const PlayerScore& b) const {
        return a.score < b.score;
        // 'true' means a has lower priority than b
    }
};

class Leaderboard {
private:
    priority_queue<PlayerScore, vector<PlayerScore>, CompareScore> playerScoresPQue;
    unordered_map<int, PlayerScore> scoresByPlayers;

    void pushItemsToPQue(
        priority_queue<PlayerScore, vector<PlayerScore>, CompareScore>& playerScoresPQue,
        list <PlayerScore>& playerScoresList) {
        for (PlayerScore playerScore : playerScoresList) {
            playerScoresPQue.push(playerScore);
        }
    }

public:
    Leaderboard() {

    }

    void addScore(int player, int score) {
        // addScore must ADD to the player's existing score, not overwrite it.
        // (Claude helped me spot this bug)

        int existingScore = 0;
        // read existing score
        auto it = scoresByPlayers.find(player);
        if (it != scoresByPlayers.end()) {
            existingScore = it->second.score;
        }

        // create new PlayerScore object with updated score
        PlayerScore playerScore = PlayerScore::of(player, existingScore + score);

        // push it into heap (priorityQue) and map
        playerScoresPQue.push(playerScore);
        scoresByPlayers[player] = playerScore;
    }

    int top(int K) {
        // create a new copy of heap
        list <PlayerScore> poppedScores;

        int scoresCount = 0;
        int scoresSum = 0;
        unordered_set<int> countedPlayers;  // guard against double-counting a player
        while (scoresCount < K) {
            // retrieve topmost PlayerScore value from PQue
            PlayerScore playerScoreFromPQue = playerScoresPQue.top();
            playerScoresPQue.pop();

            // read PlayerScore value for given player from map
            auto playerScoreFromMap = scoresByPlayers.find(playerScoreFromPQue.player);

            // check if this PlayerScore is fresh or stale
            if (playerScoreFromMap == scoresByPlayers.end()) {
                // player was reset
                continue;
            }
            if (playerScoreFromMap->second.score != playerScoreFromPQue.score) {
                // stale value that was overwritten in map but never removed from pQue
                continue;
            }
            if (countedPlayers.count(playerScoreFromPQue.player)) {
                // duplicate heap entry for an already-counted player (can happen
                // when a reset player re-reaches a prior score) -- skip it
                continue;
            }

            // otherwise its a valid (current / fresh) value
            // so add it to sum
            scoresSum += playerScoreFromMap->second.score;
            // mark this player as counted
            countedPlayers.insert(playerScoreFromPQue.player);
            // and add it to poppedScores list
            poppedScores.push_back(playerScoreFromPQue);

            // and increment scores counter
            scoresCount++;
        }

        // push back the valid items to pQue
        pushItemsToPQue(playerScoresPQue, poppedScores);

        return scoresSum;
    }

    void reset(int player) {
        scoresByPlayers.erase(player);
    }
};

/**
 * Your Leaderboard object will be instantiated and called as such:
 * Leaderboard* obj = new Leaderboard();
 * obj->addScore(playerId,score);
 * int param_2 = obj->top(K);
 * obj->reset(playerId);
 */
