// LeetCode-1196: https://leetcode.com/problems/design-file-system/

#include <string>
#include <unordered_map>
#include <vector>
#include <sstream>
#include <cstdio>
#include <iostream>
#include <cassert>

using namespace std;

#define EMPTY_NODE -1
#define DELIMITER '/'

class TrieNode {
private:
    int value;
    unordered_map<string, TrieNode*> children;

    // debugging output method generated by meta.ai
    vector<pair<string, TrieNode*>> getSortedChildren() const {
        vector<pair<string, TrieNode*>> sorted(children.begin(), children.end());
        sort(sorted.begin(), sorted.end(),
            [](const auto& a, const auto& b){ return a.first < b.first; }
        );
        return sorted;
    }

    // debugging output method generated by meta.ai
    void debugPrint(int indent = 0) const {
        for (const auto& [key, child] : getSortedChildren()) {
            for (int i = 0; i < indent; i++) cout << "  ";
            cout << "└─ " << key;
            if (child->value != -1) {
                cout << " [end, value=" << child->value << "]";
            }
            cout << "\n";
            
            child->debugPrint(indent + 1);
        }
    }

public:
    TrieNode() {
        value = EMPTY_NODE;
    }

    TrieNode(int val) {
        value = val;
    }

    bool createPath(int value, vector<string>& path, int idx) {
        int len = path.size();
        if (idx >= len) {
            // invalid: should never happen
            // printf("exiting at 1\n");
            return false;
        }

        string crrDir = path[idx];

        // printf("len=%d, idx=%d\n", len, idx);

        if (len == (idx + 1)) {
            if (children.find(crrDir) == children.end()) {
                // must insert new node here since it does not already exist
                TrieNode* newNode = new TrieNode(value);
                children[crrDir] = newNode;
                return true;
            } else {
                // can't insert new node as it already exists
                // printf("exiting at 2\n");
                return false;
            }
        }

        if (children.find(crrDir) == children.end()) {
            // can't insert new node as path doesn't exist
            // printf("exiting at 3\n");
            return false;
        } else {
            // recursively try inserting new node
            return children[crrDir]->createPath(value, path, idx + 1);
        }
    }

    int get(vector<string>& path, int idx) {
        int len = path.size();
        if (idx >= len) {
            // invalid: should never happen
            return EMPTY_NODE;
        }

        string crrDir = path[idx];

        if (len == (idx + 1)) {
            if (children.find(crrDir) == children.end()) {
                // node doesn't exist
                return EMPTY_NODE;
            } else {
                // node exists, return it's value
                return children[crrDir]->value;
            }
        }

        if (children.find(crrDir) == children.end()) {
            return EMPTY_NODE;
        } else {
            return children[crrDir]->get(path, idx + 1);
        }
    }

    void debugPrint() {
        debugPrint(0);
    }
};

class FileSystem {
private:
    TrieNode* root;
    bool debug;

    vector<string> splitPath(string path) {
        vector<string> tokens;
        stringstream ss(path);

        string token;
        while (getline(ss, token, DELIMITER)) {
            if (!token.empty()) {
                tokens.push_back(token);
            }
        }

        return tokens;
    }

    void showPath(string pathStr, vector<string>& pathVec) {
        printf("For pathStr=%s, pathVec is:-\n", pathStr.c_str());

        printf("Idx\t");
        for (int i = 0; i < pathVec.size(); i++) {
            printf("[%d]\t", i);
        }
        printf("\n");

        printf("Val\t");
        for (auto p : pathVec) {
            printf("%s\t", p.c_str());
        }
        printf("\n");
    }

    void showTrie(string when) {
        printf("%s trie is:-\n", when.c_str());
        root->debugPrint();
    }

    void showThickSeparator() {
        printf("\n========\n");
    }

    void showThinSeparator() {
        printf("\n--------\n");
    }

public:
    FileSystem() {
        root = new TrieNode();
        debug = false;
    }

    void enableDebug() {
        debug = true;
    }

    bool createPath(string pathStr, int value) {
        vector<string> pathVec = splitPath(pathStr);
        if (debug) {
            showThickSeparator();
            printf("createPath(pathStr=%s, value=%d)\n", pathStr.c_str(), value);
            showThinSeparator();

            showPath(pathStr, pathVec);
            showThinSeparator();

            showTrie("before inserting");
            showThinSeparator();
        }

        bool result = root->createPath(value, pathVec, 0);
        if (debug) {
            printf("insertion %s\n", (result ? "successful" : "failed"));
            showThinSeparator();

            showTrie("after insertion");
            showThinSeparator();

            showThickSeparator();
        }

        return result;
    }

    int get(string pathStr) {
        vector<string> pathVec = splitPath(pathStr);
        if (debug) {
            showThickSeparator();
            printf("get(pathStr=%s)\n", pathStr.c_str());
            showThinSeparator();

            showPath(pathStr, pathVec);
            showThinSeparator();
        }

        int result = root->get(pathVec, 0);
        if (debug) {
            showThinSeparator();
            printf("get result = %d\n", result);

            showThickSeparator();
        }

        return result;
    }
};

class FileSystemTest {
public:
    void test() {
        FileSystem* fs;

        fs = new FileSystem();
        // fs->enableDebug();
        assert(fs->createPath("/a", 1) == true);
        assert(fs->get("/a") == 1);

        fs = new FileSystem();
        // fs->enableDebug();
        assert(fs->createPath("/leet", 1) == true);
        assert(fs->createPath("/leet/code", 2) == true);
        assert(fs->get("/leet/code") == 2);
        assert(fs->createPath("/c/d", 1) == false);
        assert(fs->get("/c") == -1);

        fs = new FileSystem();
        // fs->enableDebug();
        assert(fs->createPath("/zt/x",710263947) == false);
        assert(fs->get("/zt/ob") == -1);
        assert(fs->get("/zt/u") == -1);
        assert(fs->get("/zt") == -1);
        assert(fs->createPath("/zt/u",99415876) == false);
        assert(fs->createPath("/zt",912783775) == true);
        assert(fs->createPath("/zt/ob",885899287) == true);
        assert(fs->get("/zt/x") == -1);
    }
};

int main() {
    FileSystemTest fsTest = FileSystemTest();

    fsTest.test();

    return 0;
}
